CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -g
LDFLAGS = -lmta_crypt -lmta_rand -lcrypto

TARGET = decrypter
SRC = decrypter.c 

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC) $(LDFLAGS)

clean:
	rm -f $(TARGET)

.PHONY: clean
